export const NAVIGATORS = {
  DEV: 'DevNavigatior',
  PUBLIC: 'PublicNavigatior',
  CORE: 'CoreTabNavigator',
  DASHBOARD: 'DashboardNavigator',
  LEAVE: 'LeaveNavigator',
  SHIFT: 'ShiftNavigator',
  NOTIFICATION: 'NotificationNavigator',
} as const;

export const SCREENS = {
  DEV_MENU: 'DevMenu',
  DEV_STORY_BOOK: 'DevStoryBook',
  SPLASH: 'Splash',
  ONBOARDING: 'Onboarding',
  SIGNUP: 'Signup',
  LOGIN: 'Login',
  SIGNUP_SUCCESSFUL: 'SignupSuccessful',
  DASHBOARD: 'Dashboard',
  LEAVES: 'Leaves',
  APPLY_LEAVE: 'ApplyLeave',
  APPLY_SHIFT: 'ApplyShift',
  SHIFTS: 'Shifts',
  NOTIFICATION: 'Notification',
  PROFILE: 'Profile',
  EDIT_PROFILE: 'EditProfile',
  ABOUT: 'About',
  LANGUAGE: 'Language',
  NOTIFICATION_SETTINGS: 'NotificationSettings',
  VIEW_LEAVE_REQUEST: 'ViewLeaveRequest',
  VIEW_SHIFT_REQUEST: 'ViewShiftRequest',
  SHIFT_REQUESTS: 'ShiftRequests',
  LEAVE_REQUESTS: 'LeaveRequests',
  ATTENDANCE: 'Attendance',
  ATTENDANCE_REPORT: 'AttendanceReport',
} as const;
